name: GSI CI

on:
  push:
    branches: [ "thirteen" ]
  pull_request:
    branches: [ "thirteen" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install build-essential repo -y

    - name: Set up work directory
      run: cd ..

    - name: Run build
      run: bash treble_build_pe/build.sh
